import type { Metadata } from "next";
// import Script from "next/script";
import { Inter } from "next/font/google";
import Navigation from "./components/_global/navigation/navigation";
import Footer from "./components/_global/footer/footer";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* <Script
        src="https://vjs.zencdn.net/8.16.1/video.min.js"
        strategy="lazyOnload"
        // onLoad={() =>
        //   console.log(`Flowplayer script loaded correctly.`)
        // }
      /> */}
      <body className={inter.className}>
        <Navigation />
        {children}
        <Footer />
      </body>
    </html>
  );
}