import type { Metadata } from "next";
import { Inter } from "next/font/google";
// import { Providers } from "./providers";
import Navigation from "./components/_global/navigation/navigation";
import Footer from "./components/_global/footer/footer";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "TP Parenting",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <Providers> */}
          <Navigation />
          {children}
          <Footer />
        {/* </Providers> */}
      </body>
    </html>
  );
}
